export const SET_REGISTER_PENDING = 'SET_REGISTER_PENDING';
export const SET_REGISTER_SUCCESS = 'SET_REGISTER_SUCCESS';
export const SET_REGISTER_ERROR = 'SET_REGISTER_ERROR';

export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';

export const SET_SUMMONER_DATA = 'SET_SUMMONER_DATA';
export const SET_SUMMONER_ERROR = 'SET_SUMMONER_ERROR';
export const SET_SUMMONER_PENDING = 'SET_SUMMONER_PENDING'

export const SET_LEAGUE_DATA = 'SET_LEAGUE_DATA';
export const SET_LEAGUE_ERROR = 'SET_LEAGUE_ERROR';
export const SET_DIVISION = 'SET_DIVISION';

export const SET_SESSION_STATE = 'SET_SESSION_STATE';

export const SET_STATE = 'SET_STATE';

export const SET_SEARCH_STATE = 'SET_SEARCH_STATE'

export const SET_LIVE_GAME_DATA = 'SET_LIVE_GAME_DATA'
export const SET_LIVE_GAME_ERROR = 'SET_LIVE_GAME_ERROR'

export const SET_SPECTATE_GAME_DATA = 'SET_SPECTATE_GAME_DATA'
export const SET_SPECTATE_GAME_PENDING = 'SET_SPECTATE_GAME_PENDING'
export const SET_SPECTATE_GAME_ERROR = 'SET_SPECTATE_GAME_ERROR'

export const SET_COLLECTION_DATA = 'SET_COLLECTION_DATA' 
export const SET_COLLECTION_ERROR = 'SET_COLLECTION_ERROR' 
export const SET_COLLECTION_FEEDBACK = 'SET_COLLECTION_FEEDBACK' 
export const SET_COLLECTION_PENDING = 'SET_COLLECTION_PENDING'
export const RESET_COLLECTION_DATA = 'RESET_COLLECTION_DATA'
