const airports = [
  { label: "AAA, Anaa Airport, Anaa" }, 
  { label: "AAE, El Mellah Airport, El Tarf" }, 
  { label: "AAL, Aalborg Airport, Norresundby" }, 
  { label: "AAM, Mala Mala, Mala Mala" }, 
  { label: "AAN, Al Ain Airport, Ayn al Faydah" }, 
  { label: "AAQ, Olkhovka Airport, Novorossiysk" }, 
  { label: "AAR, Tirstrup Airport, Kolind" }, 
  { label: "AAT, Altay Airport, Altay" }, 
  { label: "AAX, Romeu Zuma Airport, Araxá" }, 
  { label: "AAY, Al Gaidah Airport, Al Ghaydah" }, 
  { label: "ABA, Abakan, Abakan" }, 
  { label: "ABC, Los Llanos, Albacete" }, 
  { label: "ABD, , Abadan" }, 
  { label: "ABE, Lehigh Valley International Airport, Allentown" }, 
  { label: "ABI, Abilene Regional Airport, Abilene" }, 
  { label: "ABJ, Abidjan Port Bouet Airport, Abidjan" }, 
  { label: "ABK, Kabri Dar, Kabri Dar" }, 
  { label: "ABL, Ambler Airport, Kiana" }, 
  { label: "ABM, Bamaga Airport, Seisia" }, 
  { label: "ABQ, Albuquerque International Airport, Albuquerque" }, 
  { label: "ABR, Aberdeen Regional Airport, Aberdeen" }, 
  { label: "ABS, Abu Simbel Airport, Abu Simbel" }, 
  { label: "ABT, Al Baha Airport, Al Aqiq" }, 
  { label: "ABV, Abuja International Airport, Gwagwa" }, 
  { label: "ABX, Albury Airport, Albury" }, 
  { label: "ABY, Southwest Georgia Regional Airport, Albany" }, 
  { label: "ABZ, Aberdeen Dyce International Airport, Aberdeen" }, 
  { label: "ACA, General Juan N Alvarez International Airport, Acapulco" }, 
  { label: "ACC, Kotoka International Airport, Accra" }, 
  { label: "ACE, Arrecife Airport, San Bartolomé" }, 
  { label: "ACH, Altenrhein Airport, Altenrhein" }, 
  { label: "ACI, The Blaye Airport, St. Peter Port" }, 
  { label: "ACK, Nantucket Memorial Airport, Nantucket" }, 
  { label: "ACP, Sahand Airport, Sahand" }, 
  { label: "ACS, , Achinsk" }, 
  { label: "ACT, Waco Regional Airport, Waco" }, 
  { label: "ACV, Arcata Airport, Mckinleyville" }, 
  { label: "ACX, Xingyi, Xingyi" }, 
  { label: "ACY, Atlantic City International Airport, Egg Harbor City" }, 
  { label: "ACZ, Zabol A/P, Zabol" }, 
  { label: "ADA, Sakirpasa Airport, Adana" }, 
  { label: "ADB, Gaziemir Airport, Azmir" }, 
  { label: "ADD, Bole International Airport, Addis Ababa" }, 
  { label: "ADE, Aden International Airport, Ash Shaykh Uthman" }, 
  { label: "ADF, Adiyaman Airport, Adiyaman" }, 
  { label: "ADJ, Al Matar Airport, Amman" }, 
  { label: "ADK, Adak Airport, Adak" }, 
  { label: "ADL, Adelaide International Airport, Adelaide" }, 
  { label: "ADQ, Kodiak Airport, Kodiak" }, 
  { label: "ADU, Ardabil Airport, Ardabil" }, 
  { label: "ADX, Leuchars Airport, St. Andrews" }, 
  { label: "ADZ, Sesquicentenario Airport, San Andrés" }, 
  { label: "AEH, Abeche Airport, Abéché" }, 
  { label: "AEP, Aeroparque Jorge Newbery, Buenos Aires" }, 
  { label: "AER, Adler Airport, Sochi" }, 
  { label: "AES, Vigra Airport, Vigra" }, 
  { label: "AET, Allakaket Airport, Allakaket" }, 
  { label: "AEX, Alexandria International Airport, Alexandria" }, 
  { label: "AEY, Akureyri Airport, Akureyri" }, 
  { label: "AFA, San Rafael Airport, San Rafael" }, 
  { label: "AFL, Alta Floresta Airport, Alta Floresta" }, 
  { label: "AFS, Zarafshan Airport, Zarafshan" }, 
  { label: "AFT, Afutara Aerodrome, Afutara" }, 
  { label: "AFZ, Sabzevar Airport, Sabzevar" }, 
  { label: "AGA, Almassira Airport, Agadir" }, 
  { label: "AGF, La Garenne Airport, Laplume" }, 
  { label: "AGH, Angelholm Airport, Angelholm" }, 
  { label: "AGL, Wanigela, Wanigela" }, 
  { label: "AGM, Angmagssalik Airport, Angmassalik" }, 
  { label: "AGN, Angoon Airport, Angoon" }, 
  { label: "AGP, Malaga Airport, Malaga" }, 
  { label: "AGR, Agra Airport, Agra" }, 
  { label: "AGS, Bush Field Airport, Augusta" }, 
  { label: "AGT, Alejo Garcia Airport, Presidente Franco" }, 
  { label: "AGU, Aguascalientes Airport, Aguascalientes" }, 
  { label: "AGV, Acarigua, Acarigua" }, 
  { label: "AGX, Agatti Island Airport, Agatti Island" }, 
  { label: "AHB, Abha Airport, Hajlah" }, 
  { label: "AHC, Amedee Army Air Field, Herlong" }, 
  { label: "AHE, Ahe Airport, Ahe" }, 
  { label: "AHO, Alghero Airport, Alghero" }, 
  { label: "AHS, Ahuas Airport, Auas" }, 
  { label: "AHU, Cote du Rif Airport, Al Hoceima" }, 
  { label: "AIA, Alliance Municipal Airport, Alliance" }, 
  { label: "AIN, Wainwright Airport, Wainwright" }, 
  { label: "AIT, Aitutaki Airport, Aitutaki" }, 
  { label: "AIU, Atiu Island, Atiu Island" }, 
  { label: "AJA, Campo Dell Oro Airport, Ajaccio" }, 
  { label: "AJF, Al Jouf Airport, Sakakah" }, 
  { label: "AJI, Agri Airport, Agrı" }, 
  { label: "AJL, Aizwal Airport, Aizawl" }, 
  { label: "AJN, Comoros, Anjouan" }, 
  { label: "AJR, Arvidsjaur Airport, Arvidsjaur" }, 
  { label: "AJU, Santa Maria Airport, Aracaju" }, 
  { label: "AKA, Ankang Airport, Ankang" }, 
  { label: "AKB, Atka Airport, Atka" }, 
  { label: "BCN, Barcelona International Airport, El Prat de Llobregat" }, 
  { label: "CCU, Netaji Subhash Chandra Bose International Airpor, Kolkata" }, 
  { label: "CCV, Vanuatu, Craig Cove" }
   
  ]

  if (typeof module !== 'undefined') module.exports = airports;